import { type CSSProperties } from 'react';

import { brand, radii } from 'src/ui/diex-tokens';
import { safeThemeCssVariables as themeCssVariables } from 'src/ui/safe-theme-css-variables';

const border = `1px solid ${themeCssVariables.border.color.light}`;

export const aiCommandCenterStyles: Record<string, CSSProperties> = {
  root: {
    boxSizing: 'border-box',
    color: themeCssVariables.font.color.primary,
    display: 'flex',
    flexDirection: 'column',
    fontFamily: themeCssVariables.font.family,
    gap: themeCssVariables.spacing[4],
    height: 'clamp(680px, calc(100dvh - 148px), 940px)',
    overflowY: 'auto',
    padding: themeCssVariables.spacing[4],
    width: '100%',
  },
  consoleHeader: {
    alignItems: 'center',
    background: themeCssVariables.background.secondary,
    display: 'grid',
    gap: themeCssVariables.spacing[4],
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    padding: `${themeCssVariables.spacing[4]} ${themeCssVariables.spacing[5]}`,
  },
  consoleIdentity: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[3],
  },
  consoleIcon: {
    alignItems: 'center',
    background: themeCssVariables.background.transparent.blue,
    border: `1px solid ${themeCssVariables.border.color.blue}`,
    borderRadius: radii.control,
    color: brand.accent,
    display: 'flex',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  title: {
    fontSize: themeCssVariables.font.size.xl,
    fontWeight: themeCssVariables.font.weight.semiBold,
    letterSpacing: '-0.025em',
    margin: 0,
  },
  subtitle: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xs,
    lineHeight: 1.45,
    margin: `${themeCssVariables.spacing[1]} 0 0`,
  },
  systemStatus: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
  },
  pulse: {
    background: themeCssVariables.color.green,
    borderRadius: radii.circle,
    boxShadow: `0 0 0 4px ${themeCssVariables.tag.background.green}`,
    height: 8,
    width: 8,
  },
  metricStrip: {
    display: 'grid',
    gap: themeCssVariables.spacing[2],
    gridTemplateColumns: 'repeat(4, minmax(150px, 1fr))',
  },
  metricCard: {
    padding: themeCssVariables.spacing[3],
  },
  metricLabel: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    margin: 0,
    textTransform: 'uppercase',
  },
  metricValue: {
    fontSize: themeCssVariables.font.size.xl,
    fontWeight: themeCssVariables.font.weight.semiBold,
    margin: `${themeCssVariables.spacing[1]} 0 0`,
  },
  consoleGrid: {
    alignItems: 'stretch',
    display: 'grid',
    gap: themeCssVariables.spacing[4],
    gridTemplateColumns: 'minmax(280px, 0.72fr) minmax(0, 1.28fr)',
    minHeight: 520,
  },
  queueCard: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
  },
  queueHeader: {
    borderBottom: border,
  },
  filterRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: themeCssVariables.spacing[1],
    marginTop: themeCssVariables.spacing[3],
  },
  queueList: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    minHeight: 0,
    overflowY: 'auto',
  },
  queueItem: {
    background: 'transparent',
    border: 0,
    borderBottom: border,
    color: themeCssVariables.font.color.primary,
    cursor: 'pointer',
    fontFamily: themeCssVariables.font.family,
    padding: themeCssVariables.spacing[3],
    textAlign: 'left',
    width: '100%',
  },
  queueItemSelected: {
    background: brand.tint,
  },
  queueTopLine: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    justifyContent: 'space-between',
  },
  queueTitle: {
    fontSize: themeCssVariables.font.size.sm,
    fontWeight: themeCssVariables.font.weight.medium,
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  queueMeta: {
    alignItems: 'center',
    color: themeCssVariables.font.color.tertiary,
    display: 'flex',
    flexWrap: 'wrap',
    fontSize: themeCssVariables.font.size.xxs,
    gap: themeCssVariables.spacing[1],
    marginTop: themeCssVariables.spacing[2],
  },
  detailCard: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
  },
  detailHeader: {
    borderBottom: border,
  },
  detailBadges: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: themeCssVariables.spacing[1],
    marginBottom: themeCssVariables.spacing[2],
  },
  detailBody: {
    display: 'grid',
    flex: 1,
    gap: themeCssVariables.spacing[3],
    gridTemplateColumns: 'minmax(0, 1fr) minmax(220px, 0.5fr)',
    minHeight: 0,
    overflowY: 'auto',
    padding: themeCssVariables.spacing[4],
  },
  narrative: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[3],
  },
  narrativeBlock: {
    border,
    borderRadius: radii.surface,
    padding: themeCssVariables.spacing[3],
  },
  narrativeLabel: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    fontWeight: themeCssVariables.font.weight.semiBold,
    letterSpacing: '0.08em',
    margin: 0,
    textTransform: 'uppercase',
  },
  narrativeText: {
    color: themeCssVariables.font.color.secondary,
    fontSize: themeCssVariables.font.size.sm,
    lineHeight: 1.55,
    margin: `${themeCssVariables.spacing[2]} 0 0`,
    whiteSpace: 'pre-wrap',
  },
  decisionRail: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[3],
  },
  contextList: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[2],
  },
  contextButton: {
    alignItems: 'center',
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: radii.control,
    color: themeCssVariables.font.color.secondary,
    cursor: 'pointer',
    display: 'flex',
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    gap: themeCssVariables.spacing[2],
    minHeight: 36,
    padding: `0 ${themeCssVariables.spacing[2]}`,
    textAlign: 'left',
    width: '100%',
  },
  reviewTextarea: {
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: radii.control,
    boxSizing: 'border-box',
    color: themeCssVariables.font.color.primary,
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    lineHeight: 1.45,
    minHeight: 88,
    outline: 'none',
    padding: themeCssVariables.spacing[2],
    resize: 'vertical',
    width: '100%',
  },
  decisionButtons: {
    display: 'grid',
    gap: themeCssVariables.spacing[2],
    gridTemplateColumns: '1fr 1fr',
  },
  blockedExecution: {
    background: themeCssVariables.background.transparent.danger,
    border: `1px solid ${themeCssVariables.border.color.danger}`,
    borderRadius: radii.surface,
    color: themeCssVariables.font.color.danger,
    display: 'flex',
    flexDirection: 'column',
    fontSize: themeCssVariables.font.size.xs,
    gap: themeCssVariables.spacing[1],
    lineHeight: 1.45,
    padding: themeCssVariables.spacing[3],
  },
  executionPreview: {
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: radii.surface,
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[3],
    padding: themeCssVariables.spacing[3],
  },
  executionPreviewHeader: {
    alignItems: 'center',
    display: 'flex',
    fontSize: themeCssVariables.font.size.xs,
    gap: themeCssVariables.spacing[2],
  },
  executionPreviewIcon: {
    alignItems: 'center',
    background: themeCssVariables.background.transparent.blue,
    border: `1px solid ${themeCssVariables.border.color.blue}`,
    borderRadius: radii.control,
    color: brand.accent,
    display: 'flex',
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  executionPreviewMeta: {
    alignItems: 'center',
    color: themeCssVariables.font.color.tertiary,
    display: 'flex',
    fontSize: themeCssVariables.font.size.xxs,
    gap: themeCssVariables.spacing[1],
    margin: `${themeCssVariables.spacing[1]} 0 0`,
  },
  executionFactList: {
    color: themeCssVariables.font.color.secondary,
    display: 'flex',
    flexDirection: 'column',
    fontSize: themeCssVariables.font.size.xxs,
    gap: themeCssVariables.spacing[1],
  },
  executionTargets: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: themeCssVariables.spacing[1],
  },
  pipelineField: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[2],
  },
  pipelineSelect: {
    background: themeCssVariables.background.primary,
    border,
    borderRadius: radii.control,
    boxSizing: 'border-box',
    color: themeCssVariables.font.color.primary,
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    minHeight: 36,
    outline: 'none',
    padding: `0 ${themeCssVariables.spacing[2]}`,
    width: '100%',
  },
  executionGuardrail: {
    alignItems: 'center',
    background: themeCssVariables.background.transparent.blue,
    border: `1px solid ${themeCssVariables.border.color.blue}`,
    borderRadius: radii.surface,
    color: themeCssVariables.font.color.secondary,
    display: 'flex',
    fontSize: themeCssVariables.font.size.xs,
    gap: themeCssVariables.spacing[2],
    lineHeight: 1.45,
    padding: themeCssVariables.spacing[3],
  },
  executionButtons: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: themeCssVariables.spacing[2],
  },
  auditGrid: {
    display: 'grid',
    gap: themeCssVariables.spacing[2],
    gridTemplateColumns: 'repeat(4, minmax(200px, 1fr))',
  },
  auditCard: {
    minHeight: 108,
  },
  empty: {
    alignItems: 'center',
    color: themeCssVariables.font.color.tertiary,
    display: 'flex',
    flex: 1,
    fontSize: themeCssVariables.font.size.sm,
    justifyContent: 'center',
    minHeight: 180,
    padding: themeCssVariables.spacing[4],
    textAlign: 'center',
  },
};
