#
# Crowdin CLI configuration for Documentation translations
# See https://crowdin.github.io/crowdin-cli/configuration for more information
#

"project_id": 2
"preserve_hierarchy": true
"base_url": "https://diex.api.crowdin.com"
"base_path": ".."

files: [
  {
    "source": "packages/diex-docs/getting-started/**/*.mdx",
    "translation": "packages/diex-docs/l/%two_letters_code%/getting-started/**/%original_file_name%",
    "type": "mdx_v2",
    "exclude_code_blocks": true,
    "excluded_front_matter_elements": ["icon"],
  },
  {
    "source": "packages/diex-docs/user-guide/**/*.mdx",
    "translation": "packages/diex-docs/l/%two_letters_code%/user-guide/**/%original_file_name%",
    "type": "mdx_v2",
    "exclude_code_blocks": true,
    "excluded_front_matter_elements": ["icon"],
  },
  {
    "source": "packages/diex-docs/developers/**/*.mdx",
    "translation": "packages/diex-docs/l/%two_letters_code%/developers/**/%original_file_name%",
    "type": "mdx_v2",
    "exclude_code_blocks": true,
    "excluded_front_matter_elements": ["icon"],
  },
  {
    "source": "packages/diex-docs/diex-ui/**/*.mdx",
    "translation": "packages/diex-docs/l/%two_letters_code%/diex-ui/**/%original_file_name%",
    "type": "mdx_v2",
    "exclude_code_blocks": true,
    "excluded_front_matter_elements": ["icon"],
  },
  {
    #
    # Navigation labels template - translated into per-locale navigation.json
    #
    "source": "packages/diex-docs/navigation/navigation.template.json",
    "translation": "packages/diex-docs/l/%two_letters_code%/navigation.json",
  }
]
