export enum OnboardingStatus {
  PLAN_REQUIRED = 'PLAN_REQUIRED',
  WORKSPACE_APPROVAL_PENDING = 'WORKSPACE_APPROVAL_PENDING',
  WORKSPACE_ACTIVATION = 'WORKSPACE_ACTIVATION',
  PROFILE_CREATION = 'PROFILE_CREATION',
  SYNC_EMAIL = 'SYNC_EMAIL',
  APPS_INSTALLATION = 'APPS_INSTALLATION',
  INVITE_TEAM = 'INVITE_TEAM',
  DIEX_WORKSPACE_SETUP = 'DIEX_WORKSPACE_SETUP',
  COMPLETED = 'COMPLETED',
}
