import { type CSSProperties } from 'react';

import { safeThemeCssVariables as themeCssVariables } from 'src/ui/safe-theme-css-variables';

const border = `1px solid ${themeCssVariables.border.color.light}`;

export const renewalCommandCenterStyles: Record<string, CSSProperties> = {
  root: {
    boxSizing: 'border-box',
    color: themeCssVariables.font.color.primary,
    display: 'flex',
    flexDirection: 'column',
    fontFamily: themeCssVariables.font.family,
    gap: themeCssVariables.spacing[4],
    height: 'clamp(700px, calc(100dvh - 148px), 980px)',
    overflowY: 'auto',
    padding: themeCssVariables.spacing[4],
    width: '100%',
  },
  controlHeader: {
    alignItems: 'stretch',
    background: `linear-gradient(120deg, ${themeCssVariables.background.transparent.success}, ${themeCssVariables.background.primary} 58%, ${themeCssVariables.background.transparent.blue})`,
    display: 'grid',
    gap: themeCssVariables.spacing[5],
    gridTemplateColumns: 'minmax(0, 1fr) minmax(310px, 0.42fr)',
    minHeight: 164,
    overflow: 'hidden',
    padding: themeCssVariables.spacing[5],
  },
  eyebrow: {
    alignItems: 'center',
    color: themeCssVariables.accent.primary,
    display: 'flex',
    fontSize: themeCssVariables.font.size.xxs,
    fontWeight: themeCssVariables.font.weight.semiBold,
    gap: themeCssVariables.spacing[1],
    letterSpacing: '0.12em',
    margin: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: themeCssVariables.font.color.primary,
    fontSize: 30,
    fontWeight: themeCssVariables.font.weight.semiBold,
    letterSpacing: '-0.035em',
    lineHeight: 1.12,
    margin: `${themeCssVariables.spacing[2]} 0`,
  },
  subtitle: {
    color: themeCssVariables.font.color.secondary,
    fontSize: themeCssVariables.font.size.sm,
    lineHeight: 1.55,
    margin: 0,
    maxWidth: 720,
  },
  createBox: {
    alignSelf: 'center',
    background: themeCssVariables.background.primary,
    border,
    borderRadius: themeCssVariables.border.radius.md,
    boxShadow: themeCssVariables.boxShadow.light,
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[2],
    padding: themeCssVariables.spacing[4],
  },
  createLabel: {
    color: themeCssVariables.font.color.secondary,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    margin: 0,
  },
  createRow: {
    display: 'grid',
    gap: themeCssVariables.spacing[2],
    gridTemplateColumns: 'minmax(0, 1fr) auto',
  },
  input: {
    background: themeCssVariables.background.primary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    boxSizing: 'border-box',
    color: themeCssVariables.font.color.primary,
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    minHeight: themeCssVariables.spacing[8],
    outline: 'none',
    padding: `0 ${themeCssVariables.spacing[2]}`,
    width: '100%',
  },
  textarea: {
    background: themeCssVariables.background.primary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    boxSizing: 'border-box',
    color: themeCssVariables.font.color.primary,
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    lineHeight: 1.45,
    minHeight: 88,
    outline: 'none',
    padding: themeCssVariables.spacing[2],
    resize: 'vertical',
    width: '100%',
  },
  metricLedger: {
    display: 'grid',
    gap: 1,
    gridTemplateColumns: 'repeat(5, minmax(140px, 1fr))',
    overflowX: 'auto',
  },
  metricCell: {
    background: themeCssVariables.background.secondary,
    border,
    minHeight: 86,
    padding: themeCssVariables.spacing[3],
  },
  metricLabel: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    letterSpacing: '0.06em',
    margin: 0,
    textTransform: 'uppercase',
  },
  metricValue: {
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.lg,
    fontWeight: themeCssVariables.font.weight.semiBold,
    margin: `${themeCssVariables.spacing[1]} 0 0`,
  },
  metricNote: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    margin: `${themeCssVariables.spacing[1]} 0 0`,
  },
  sectionHeader: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    justifyContent: 'space-between',
    padding: themeCssVariables.spacing[3],
  },
  sectionTitle: {
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.sm,
    fontWeight: themeCssVariables.font.weight.semiBold,
    margin: 0,
  },
  sectionNote: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xs,
    margin: `${themeCssVariables.spacing[1]} 0 0`,
  },
  stageRail: {
    display: 'grid',
    gap: themeCssVariables.spacing[2],
    gridTemplateColumns: 'repeat(6, minmax(180px, 1fr))',
    overflowX: 'auto',
    padding: `0 ${themeCssVariables.spacing[3]} ${themeCssVariables.spacing[3]}`,
  },
  stageRailItem: {
    alignItems: 'center',
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    display: 'grid',
    gap: themeCssVariables.spacing[2],
    gridTemplateColumns: '24px minmax(0, 1fr) auto',
    minHeight: 52,
    padding: themeCssVariables.spacing[2],
  },
  stageNumber: {
    alignItems: 'center',
    background: themeCssVariables.background.tertiary,
    borderRadius: themeCssVariables.border.radius.pill,
    color: themeCssVariables.font.color.secondary,
    display: 'flex',
    fontSize: themeCssVariables.font.size.xxs,
    fontWeight: themeCssVariables.font.weight.semiBold,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  stageName: {
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    margin: 0,
  },
  stageValue: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    margin: 0,
    textAlign: 'right',
  },
  board: {
    display: 'grid',
    gap: themeCssVariables.spacing[3],
    gridTemplateColumns: 'repeat(6, minmax(250px, 1fr))',
    minHeight: 300,
    overflowX: 'auto',
    padding: themeCssVariables.spacing[3],
  },
  boardColumn: {
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: themeCssVariables.border.radius.md,
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[2],
    minHeight: 280,
    padding: themeCssVariables.spacing[2],
  },
  columnHeader: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    padding: themeCssVariables.spacing[1],
  },
  columnCards: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[2],
  },
  renewalCard: {
    background: themeCssVariables.background.primary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.primary,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: themeCssVariables.font.family,
    gap: themeCssVariables.spacing[2],
    padding: themeCssVariables.spacing[3],
    textAlign: 'left',
    width: '100%',
  },
  selectedCard: {
    border: `1px solid ${themeCssVariables.border.color.blue}`,
    boxShadow: themeCssVariables.boxShadow.light,
  },
  cardName: {
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.semiBold,
    lineHeight: 1.35,
    margin: 0,
  },
  cardMeta: {
    alignItems: 'center',
    color: themeCssVariables.font.color.tertiary,
    display: 'flex',
    fontSize: themeCssVariables.font.size.xxs,
    gap: themeCssVariables.spacing[1],
    justifyContent: 'space-between',
  },
  cardAction: {
    color: themeCssVariables.font.color.secondary,
    fontSize: themeCssVariables.font.size.xxs,
    lineHeight: 1.4,
    margin: 0,
  },
  emptyColumn: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    margin: 'auto',
    padding: themeCssVariables.spacing[4],
    textAlign: 'center',
  },
  workbench: {
    display: 'grid',
    gap: themeCssVariables.spacing[4],
    gridTemplateColumns: 'minmax(0, 1.35fr) minmax(300px, 0.65fr)',
  },
  detailHeader: {
    alignItems: 'flex-start',
    display: 'flex',
    gap: themeCssVariables.spacing[3],
    justifyContent: 'space-between',
  },
  detailTitle: {
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.md,
    fontWeight: themeCssVariables.font.weight.semiBold,
    margin: 0,
  },
  badgeRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: themeCssVariables.spacing[1],
    marginTop: themeCssVariables.spacing[2],
  },
  formGrid: {
    display: 'grid',
    gap: themeCssVariables.spacing[3],
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[1],
  },
  fieldWide: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[1],
    gridColumn: 'span 3',
  },
  fieldLabel: {
    color: themeCssVariables.font.color.secondary,
    fontSize: themeCssVariables.font.size.xxs,
    fontWeight: themeCssVariables.font.weight.medium,
  },
  actionBar: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: themeCssVariables.spacing[2],
    marginTop: themeCssVariables.spacing[3],
  },
  timeline: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[3],
  },
  timelineItem: {
    display: 'grid',
    gap: themeCssVariables.spacing[2],
    gridTemplateColumns: '10px minmax(0, 1fr)',
  },
  timelineDot: {
    background: themeCssVariables.accent.primary,
    borderRadius: themeCssVariables.border.radius.pill,
    height: 8,
    marginTop: themeCssVariables.spacing[1],
    width: 8,
  },
  timelineSummary: {
    color: themeCssVariables.font.color.secondary,
    fontSize: themeCssVariables.font.size.xs,
    lineHeight: 1.4,
    margin: 0,
  },
  timelineMeta: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    margin: `${themeCssVariables.spacing[1]} 0 0`,
  },
  emptyState: {
    alignItems: 'center',
    color: themeCssVariables.font.color.tertiary,
    display: 'flex',
    flexDirection: 'column',
    fontSize: themeCssVariables.font.size.xs,
    gap: themeCssVariables.spacing[2],
    justifyContent: 'center',
    minHeight: 220,
    padding: themeCssVariables.spacing[5],
    textAlign: 'center',
  },
};
