import { type CSSProperties } from 'react';

import { brand, radii } from 'src/ui/diex-tokens';
import { safeThemeCssVariables as themeCssVariables } from 'src/ui/safe-theme-css-variables';

const border = `1px solid ${themeCssVariables.border.color.light}`;

export const customerSuccessCommandCenterStyles: Record<string, CSSProperties> =
  {
    root: {
      boxSizing: 'border-box',
      color: themeCssVariables.font.color.primary,
      display: 'flex',
      flexDirection: 'column',
      fontFamily: themeCssVariables.font.family,
      gap: themeCssVariables.spacing[4],
      height: 'clamp(720px, calc(100dvh - 148px), 1040px)',
      overflowY: 'auto',
      padding: themeCssVariables.spacing[4],
      width: '100%',
    },
    hero: {
      alignItems: 'stretch',
      background: `linear-gradient(125deg, ${themeCssVariables.background.primary} 0%, ${themeCssVariables.background.transparent.blue} 100%)`,
      display: 'grid',
      gap: themeCssVariables.spacing[5],
      gridTemplateColumns: 'minmax(0, 1fr) 280px',
      padding: themeCssVariables.spacing[5],
    },
    heroCopy: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
      minWidth: 0,
    },
    eyebrow: {
      alignItems: 'center',
      color: brand.accent,
      display: 'flex',
      fontSize: themeCssVariables.font.size.xxs,
      fontWeight: themeCssVariables.font.weight.semiBold,
      gap: themeCssVariables.spacing[1],
      letterSpacing: '0.08em',
      margin: 0,
    },
    title: {
      fontSize: themeCssVariables.font.size.xxl,
      fontWeight: themeCssVariables.font.weight.semiBold,
      letterSpacing: '-0.035em',
      lineHeight: 1.08,
      margin: `${themeCssVariables.spacing[2]} 0 0`,
    },
    subtitle: {
      color: themeCssVariables.font.color.tertiary,
      fontSize: themeCssVariables.font.size.sm,
      lineHeight: 1.55,
      margin: `${themeCssVariables.spacing[2]} 0 0`,
      maxWidth: 720,
    },
    heroActions: {
      alignItems: 'center',
      display: 'flex',
      flexWrap: 'wrap',
      gap: themeCssVariables.spacing[2],
      marginTop: themeCssVariables.spacing[4],
    },
    healthPulse: {
      alignItems: 'center',
      borderLeft: border,
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[3],
      justifyContent: 'center',
      paddingLeft: themeCssVariables.spacing[5],
    },
    healthRing: {
      alignItems: 'center',
      borderRadius: radii.circle,
      display: 'flex',
      height: 132,
      justifyContent: 'center',
      position: 'relative',
      width: 132,
    },
    healthRingCenter: {
      alignItems: 'center',
      background: themeCssVariables.background.primary,
      border: border,
      borderRadius: radii.circle,
      display: 'flex',
      flexDirection: 'column',
      height: 86,
      justifyContent: 'center',
      position: 'absolute',
      width: 86,
    },
    healthRingValue: {
      fontSize: themeCssVariables.font.size.xl,
      fontWeight: themeCssVariables.font.weight.semiBold,
      lineHeight: 1,
    },
    smallMuted: {
      color: themeCssVariables.font.color.tertiary,
      fontSize: themeCssVariables.font.size.xxs,
      lineHeight: 1.4,
      margin: 0,
    },
    metricGrid: {
      display: 'grid',
      gap: themeCssVariables.spacing[2],
      gridTemplateColumns: 'repeat(4, minmax(150px, 1fr))',
    },
    metricCard: {
      minHeight: 104,
      padding: themeCssVariables.spacing[3],
    },
    metricTop: {
      alignItems: 'center',
      display: 'flex',
      gap: themeCssVariables.spacing[2],
      justifyContent: 'space-between',
    },
    metricLabel: {
      color: themeCssVariables.font.color.tertiary,
      fontSize: themeCssVariables.font.size.xxs,
      margin: 0,
    },
    metricValue: {
      fontSize: themeCssVariables.font.size.xl,
      fontWeight: themeCssVariables.font.weight.semiBold,
      margin: themeCssVariables.spacing[2] + ' 0 0',
    },
    handoffCard: {
      display: 'flex',
      flexDirection: 'column',
      minHeight: 0,
    },
    handoffHeader: {
      borderBottom: border,
      paddingBottom: themeCssVariables.spacing[1],
    },
    handoffGrid: {
      display: 'grid',
      gap: 0,
      gridTemplateColumns:
        'minmax(220px, 0.66fr) minmax(300px, 1fr) minmax(280px, 1fr)',
      padding: 0,
    },
    handoffQueue: {
      borderRight: border,
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[2],
      minWidth: 0,
      padding: themeCssVariables.spacing[3],
    },
    handoffQueueList: {
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[1],
      maxHeight: 520,
      overflowY: 'auto',
    },
    handoffOpportunity: {
      background: themeCssVariables.background.secondary,
      border,
      borderRadius: radii.surface,
      color: themeCssVariables.font.color.primary,
      cursor: 'pointer',
      display: 'flex',
      flexDirection: 'column',
      fontFamily: themeCssVariables.font.family,
      gap: themeCssVariables.spacing[1],
      padding: themeCssVariables.spacing[2],
      textAlign: 'left',
      width: '100%',
    },
    handoffOpportunitySelected: {
      background: brand.tint,
      borderColor: brand.border,
    },
    handoffForm: {
      borderRight: border,
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[3],
      minWidth: 0,
      padding: themeCssVariables.spacing[3],
    },
    handoffFieldGrid: {
      display: 'grid',
      gap: themeCssVariables.spacing[2],
      gridTemplateColumns: '1fr 0.42fr',
    },
    handoffField: {
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[1],
    },
    handoffInput: {
      background: themeCssVariables.background.primary,
      border,
      borderRadius: radii.control,
      boxSizing: 'border-box',
      color: themeCssVariables.font.color.primary,
      fontFamily: themeCssVariables.font.family,
      fontSize: themeCssVariables.font.size.xs,
      minHeight: 36,
      outline: 'none',
      padding: `0 ${themeCssVariables.spacing[2]}`,
      width: '100%',
    },
    handoffTextarea: {
      background: themeCssVariables.background.primary,
      border,
      borderRadius: radii.control,
      boxSizing: 'border-box',
      color: themeCssVariables.font.color.primary,
      fontFamily: themeCssVariables.font.family,
      fontSize: themeCssVariables.font.size.xs,
      lineHeight: 1.45,
      minHeight: 76,
      outline: 'none',
      padding: themeCssVariables.spacing[2],
      resize: 'vertical',
      width: '100%',
    },
    handoffPreview: {
      background: themeCssVariables.background.secondary,
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[3],
      minWidth: 0,
      padding: themeCssVariables.spacing[3],
    },
    handoffPlanSummary: {
      alignItems: 'flex-start',
      display: 'flex',
      gap: themeCssVariables.spacing[2],
      justifyContent: 'space-between',
    },
    handoffMilestones: {
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[1],
    },
    handoffMilestone: {
      alignItems: 'center',
      background: themeCssVariables.background.primary,
      border,
      borderRadius: radii.surface,
      display: 'grid',
      fontSize: themeCssVariables.font.size.xs,
      gap: themeCssVariables.spacing[2],
      gridTemplateColumns: '28px minmax(0, 1fr)',
      padding: themeCssVariables.spacing[2],
    },
    handoffMilestoneIndex: {
      alignItems: 'center',
      background: themeCssVariables.background.transparent.blue,
      border: `1px solid ${themeCssVariables.border.color.blue}`,
      borderRadius: radii.circle,
      color: brand.accent,
      display: 'flex',
      fontSize: themeCssVariables.font.size.xxs,
      fontWeight: themeCssVariables.font.weight.semiBold,
      height: 24,
      justifyContent: 'center',
      width: 24,
    },
    handoffTask: {
      alignItems: 'center',
      background: themeCssVariables.background.transparent.blue,
      border: `1px solid ${themeCssVariables.border.color.blue}`,
      borderRadius: radii.surface,
      display: 'flex',
      fontSize: themeCssVariables.font.size.xs,
      gap: themeCssVariables.spacing[2],
      padding: themeCssVariables.spacing[2],
    },
    handoffWarning: {
      background: themeCssVariables.background.transparent.danger,
      border: `1px solid ${themeCssVariables.border.color.danger}`,
      borderRadius: radii.surface,
      color: themeCssVariables.font.color.danger,
      fontSize: themeCssVariables.font.size.xxs,
      lineHeight: 1.4,
      margin: 0,
      padding: themeCssVariables.spacing[2],
    },
    handoffGuardrail: {
      alignItems: 'center',
      color: themeCssVariables.font.color.tertiary,
      display: 'flex',
      flex: 1,
      flexDirection: 'column',
      gap: themeCssVariables.spacing[3],
      justifyContent: 'center',
      minHeight: 260,
      textAlign: 'center',
    },
    journeyCard: {
      padding: themeCssVariables.spacing[4],
    },
    sectionHeading: {
      alignItems: 'center',
      display: 'flex',
      gap: themeCssVariables.spacing[3],
      justifyContent: 'space-between',
      marginBottom: themeCssVariables.spacing[3],
    },
    journeyTrack: {
      display: 'grid',
      gap: themeCssVariables.spacing[2],
      gridTemplateColumns: 'repeat(6, minmax(120px, 1fr))',
    },
    journeyStage: {
      background: themeCssVariables.background.secondary,
      border,
      borderRadius: radii.surface,
      color: themeCssVariables.font.color.primary,
      cursor: 'pointer',
      fontFamily: themeCssVariables.font.family,
      minHeight: 88,
      padding: themeCssVariables.spacing[3],
      position: 'relative',
      textAlign: 'left',
    },
    journeyStageSelected: {
      background: themeCssVariables.background.transparent.blue,
      borderColor: themeCssVariables.border.color.blue,
      boxShadow: `inset 0 -2px 0 ${brand.accent}`,
    },
    journeyCount: {
      fontSize: themeCssVariables.font.size.lg,
      fontWeight: themeCssVariables.font.weight.semiBold,
      margin: `${themeCssVariables.spacing[2]} 0 0`,
    },
    workspaceGrid: {
      alignItems: 'stretch',
      display: 'grid',
      gap: themeCssVariables.spacing[4],
      gridTemplateColumns: 'minmax(300px, 0.78fr) minmax(0, 1.42fr)',
      minHeight: 610,
    },
    portfolioCard: {
      display: 'flex',
      flexDirection: 'column',
      minHeight: 0,
    },
    portfolioHeader: {
      borderBottom: border,
    },
    filterRow: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: themeCssVariables.spacing[1],
      marginTop: themeCssVariables.spacing[3],
    },
    portfolioList: {
      display: 'flex',
      flex: 1,
      flexDirection: 'column',
      minHeight: 0,
      overflowY: 'auto',
    },
    planButton: {
      background: 'transparent',
      border: 0,
      borderBottom: border,
      color: themeCssVariables.font.color.primary,
      cursor: 'pointer',
      fontFamily: themeCssVariables.font.family,
      padding: themeCssVariables.spacing[3],
      textAlign: 'left',
      width: '100%',
    },
    planButtonSelected: {
      background: brand.tint,
    },
    planTop: {
      alignItems: 'center',
      display: 'flex',
      gap: themeCssVariables.spacing[2],
      justifyContent: 'space-between',
    },
    planName: {
      fontSize: themeCssVariables.font.size.sm,
      fontWeight: themeCssVariables.font.weight.medium,
      margin: 0,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    planCompany: {
      color: themeCssVariables.font.color.tertiary,
      fontSize: themeCssVariables.font.size.xxs,
      margin: `${themeCssVariables.spacing[1]} 0 ${themeCssVariables.spacing[2]}`,
    },
    planMeta: {
      alignItems: 'center',
      color: themeCssVariables.font.color.tertiary,
      display: 'flex',
      flexWrap: 'wrap',
      fontSize: themeCssVariables.font.size.xxs,
      gap: themeCssVariables.spacing[2],
      justifyContent: 'space-between',
      marginTop: themeCssVariables.spacing[2],
    },
    detailCard: {
      display: 'flex',
      flexDirection: 'column',
      minHeight: 0,
    },
    detailHeader: {
      borderBottom: border,
    },
    detailBody: {
      display: 'grid',
      flex: 1,
      gap: themeCssVariables.spacing[4],
      gridTemplateColumns: 'minmax(0, 1.2fr) minmax(250px, 0.8fr)',
      minHeight: 0,
      overflowY: 'auto',
      padding: themeCssVariables.spacing[4],
    },
    detailColumn: {
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[3],
      minWidth: 0,
    },
    factGrid: {
      display: 'grid',
      gap: themeCssVariables.spacing[2],
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    fact: {
      background: themeCssVariables.background.secondary,
      border,
      borderRadius: radii.surface,
      padding: themeCssVariables.spacing[3],
    },
    factValue: {
      fontSize: themeCssVariables.font.size.sm,
      fontWeight: themeCssVariables.font.weight.medium,
      margin: `${themeCssVariables.spacing[1]} 0 0`,
    },
    narrative: {
      color: themeCssVariables.font.color.secondary,
      fontSize: themeCssVariables.font.size.sm,
      lineHeight: 1.55,
      margin: 0,
      whiteSpace: 'pre-wrap',
    },
    milestoneList: {
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[2],
    },
    milestoneButton: {
      alignItems: 'center',
      background: themeCssVariables.background.secondary,
      border,
      borderRadius: radii.control,
      color: themeCssVariables.font.color.primary,
      cursor: 'pointer',
      display: 'grid',
      fontFamily: themeCssVariables.font.family,
      gap: themeCssVariables.spacing[2],
      gridTemplateColumns: '24px minmax(0, 1fr) auto',
      minHeight: 52,
      padding: themeCssVariables.spacing[2],
      textAlign: 'left',
      width: '100%',
    },
    milestoneButtonSelected: {
      background: brand.tint,
      borderColor: brand.border,
    },
    milestoneActionCard: {
      background: themeCssVariables.background.primary,
      marginTop: themeCssVariables.spacing[3],
    },
    milestoneActionBody: {
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[3],
    },
    milestoneActionGrid: {
      display: 'grid',
      gap: themeCssVariables.spacing[2],
      gridTemplateColumns: 'minmax(0, 1.5fr) minmax(120px, 0.5fr)',
    },
    milestoneActionClosed: {
      alignItems: 'center',
      background: themeCssVariables.background.transparent.blue,
      border: `1px solid ${themeCssVariables.border.color.blue}`,
      borderRadius: radii.surface,
      display: 'flex',
      gap: themeCssVariables.spacing[3],
      padding: themeCssVariables.spacing[3],
    },
    milestoneActionBlocked: {
      alignItems: 'center',
      background: themeCssVariables.background.transparent.danger,
      border: `1px solid ${themeCssVariables.border.color.danger}`,
      borderRadius: radii.surface,
      color: themeCssVariables.font.color.danger,
      display: 'flex',
      fontSize: themeCssVariables.font.size.xs,
      gap: themeCssVariables.spacing[2],
      padding: themeCssVariables.spacing[2],
    },
    milestoneActionPreview: {
      background: themeCssVariables.background.secondary,
      border,
      borderRadius: radii.surface,
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[3],
      padding: themeCssVariables.spacing[3],
    },
    milestoneActionEffectList: {
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[1],
      marginTop: themeCssVariables.spacing[2],
    },
    reviewCard: {
      display: 'flex',
      flexDirection: 'column',
      gap: themeCssVariables.spacing[3],
    },
    reviewBlock: {
      border: `1px solid ${brand.border}`,
      paddingLeft: themeCssVariables.spacing[3],
    },
    reviewActions: {
      display: 'grid',
      gap: themeCssVariables.spacing[2],
      gridTemplateColumns: '1fr',
    },
    renewalGrid: {
      display: 'grid',
      gap: themeCssVariables.spacing[2],
      gridTemplateColumns: 'repeat(3, minmax(220px, 1fr))',
    },
    renewalCard: {
      cursor: 'pointer',
      minHeight: 132,
      padding: themeCssVariables.spacing[3],
    },
    renewalDate: {
      color: brand.accent,
      fontSize: themeCssVariables.font.size.xs,
      fontWeight: themeCssVariables.font.weight.semiBold,
      margin: 0,
    },
    empty: {
      alignItems: 'center',
      color: themeCssVariables.font.color.tertiary,
      display: 'flex',
      flex: 1,
      fontSize: themeCssVariables.font.size.sm,
      justifyContent: 'center',
      minHeight: 180,
      padding: themeCssVariables.spacing[4],
      textAlign: 'center',
    },
  };
