import { LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER } from 'twenty-shared/application';

import { type AllStandardObjectName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-name.type';

export const METADATA_IDENTITY_APPLICATION_UNIVERSAL_IDENTIFIER_BY_STANDARD_OBJECT_NAME =
  {
    aiAction: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    commercialSignal: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    customerRenewal: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    customerRenewalEvent: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    diexAccessRequest: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    diexWorkspaceContext: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    workspaceArchitectureArtifact:
      LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxAutomation: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxConversation: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxConversationEvent: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxConversationLabel: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxLabel: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxMacro: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxMention: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxMessage: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxSavedReply: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxTeam: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxTeamMember: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    offer: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    successMilestone: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
    successPlan: LEGACY_METADATA_APPLICATION_UNIVERSAL_IDENTIFIER,
  } as const satisfies Partial<Record<AllStandardObjectName, string>>;
