import { DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER } from 'twenty-shared/application';

import { type AllStandardObjectName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-name.type';

export const METADATA_IDENTITY_APPLICATION_UNIVERSAL_IDENTIFIER_BY_STANDARD_OBJECT_NAME =
  {
    aiAction: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    commercialSignal: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    customerRenewal: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    customerRenewalEvent: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    diexAccessRequest: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    diexWorkspaceContext: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxAutomation: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxConversation: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxConversationEvent: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxConversationLabel: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxLabel: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxMacro: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxMention: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxMessage: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxSavedReply: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxTeam: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    inboxTeamMember: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    offer: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    successMilestone: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
    successPlan: DIEX_CORE_APPLICATION_UNIVERSAL_IDENTIFIER,
  } as const satisfies Partial<Record<AllStandardObjectName, string>>;
