name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

env:
  DIEX_VERSION: latest

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Spawn Diex test instance
        id: diex
        uses: diexhq/diex/.github/actions/spawn-diex-app-dev-test@main
        with:
          diex-version: ${{ env.DIEX_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run integration tests
        run: yarn test
        env:
          DIEX_API_URL: ${{ steps.diex.outputs.server-url }}
          DIEX_API_KEY: ${{ steps.diex.outputs.api-key }}
