import { defineSkill } from 'twenty-sdk/define';

export const COMMERCIAL_OPERATING_LOOP_SKILL_UNIVERSAL_IDENTIFIER =
  'a7f2c4d1-59be-4d0e-9a3b-6c0f8e2d4b17';

export default defineSkill({
  universalIdentifier: COMMERCIAL_OPERATING_LOOP_SKILL_UNIVERSAL_IDENTIFIER,
  name: 'diex-commercial-operating-loop',
  label: 'Rotina comercial Diex',
  icon: 'IconRouteAltLeft',
  description:
    'Como operar este CRM de ponta a ponta: onde agir agora, como responder um WhatsApp com contexto e como desdobrar uma reunião em oportunidades e tarefas.',
  content: [
    '# Rotina comercial Diex',
    '',
    'Este workspace atende clientes por WhatsApp e registra a operação comercial no CRM. As ferramentas abaixo existem para você trabalhar com fatos, não com suposição.',
    '',
    '## 1. Onde agir agora',
    '',
    'Chame `get-diex-commercial-priorities`. Ela devolve filas, não opinião:',
    '',
    '- `waitingOnUs` — o cliente escreveu por último e ninguém respondeu. `waitingSinceMinutes` é o tamanho da espera. Comece aqui.',
    '- `followUpsDue` — follow-up combinado que venceu.',
    '- `overdueTasks` — tarefa com prazo estourado.',
    '- `stalledOpportunities` — negócio cujo próximo passo venceu ou já marcado como risco alto.',
    '- `renewalsAtRisk` — renovação em risco, com o motivo registrado.',
    '',
    'Fila vazia significa fila limpa. Não invente trabalho para preencher.',
    '',
    '## 2. Responder uma conversa de WhatsApp',
    '',
    '1. `get-diex-inbox-conversation-context` com o `conversationId` (ou o telefone em `contactSearch`). Traz a transcrição completa, as notas internas, o contato, a empresa, a oportunidade, as tarefas abertas e os sinais.',
    '2. Em mensagens de áudio, `transcription` é o que o cliente **falou**. Trate como fala dele e cite como fala. Quando `transcriptionStatus` não é `DONE`, o áudio não virou texto e você não sabe o que foi dito: o operador consegue ouvi-lo na inbox, então peça que ele abra o áudio em vez de pedir ao cliente que repita por escrito o que já falou.',
    '3. `get-diex-workspace-context` antes de escrever: use o tom de voz e as regras comerciais de lá, e nunca produza afirmação listada como proibida.',
    '4. Redija o rascunho e entregue ao operador. **Você não envia.** O envio exige a confirmação explícita dele na inbox, e há uma janela de 24 horas desde a última mensagem recebida — fora dela é preciso consentimento registrado no contato.',
    '5. Registre o que a conversa revelou: sinal comercial quando houver evidência de intenção, objeção ou risco; tarefa quando ficou combinado um próximo passo.',
    '',
    '## 3. Desdobrar uma reunião',
    '',
    '1. `register-diex-meeting-transcript` com o texto integral, e `companyId` ou `companySearch`. A transcrição fica gravada como nota ligada à empresa, ao contato e à oportunidade.',
    '2. Se a busca por nome for ambígua, a ferramenta devolve candidatos e **não grava nada** — confirme qual empresa antes de repetir a chamada.',
    '3. A resposta traz as oportunidades e tarefas que já existem naquele cliente. Atualize-as em vez de criar parecidas.',
    '4. Desdobre com as ferramentas do CRM: `create_one_task` para cada próximo passo com prazo e responsável, `create_one_opportunity` apenas quando houve intenção real de compra, `create_one_commercial_signal` para o que explica urgência ou risco. Ligue cada item ao cliente e cite no corpo o trecho da reunião que o sustenta.',
    '',
    '## 4. Regras que valem em tudo',
    '',
    '- Separe fato, inferência e recomendação. Fato é o que está no CRM ou na transcrição; o resto é seu e deve estar rotulado.',
    '- Quando faltar informação, nomeie a lacuna menor que resolveria a dúvida. Ausência de dado não é sinal negativo.',
    '- Score, previsão e probabilidade apoiam decisão e não são promessa.',
    '- Nunca invente valor, prazo, consentimento ou fala do cliente.',
    '- Nada aqui autoriza mensagem externa, mudança de etapa ou campanha sem pedido explícito do operador.',
    '- Nunca peça nem exponha credencial, token ou QR Code.',
  ].join('\n'),
});
