import { type CSSProperties } from 'react';

import { safeThemeCssVariables as themeCssVariables } from 'src/ui/safe-theme-css-variables';

export const commercialIntelligenceStyles: Record<string, CSSProperties> = {
  root: {
    boxSizing: 'border-box',
    color: themeCssVariables.font.color.primary,
    display: 'flex',
    flexDirection: 'column',
    fontFamily: themeCssVariables.font.family,
    gap: themeCssVariables.spacing[4],
    height: 'clamp(660px, calc(100dvh - 148px), 920px)',
    overflowY: 'auto',
    padding: themeCssVariables.spacing[4],
    width: '100%',
  },
  hero: {
    alignItems: 'stretch',
    background: `linear-gradient(135deg, ${themeCssVariables.background.transparent.blue}, ${themeCssVariables.background.primary})`,
    display: 'grid',
    gap: themeCssVariables.spacing[4],
    gridTemplateColumns: 'minmax(0, 1.5fr) minmax(220px, 0.5fr)',
    minHeight: 190,
    overflow: 'hidden',
    padding: themeCssVariables.spacing[5],
    position: 'relative',
  },
  heroCopy: {
    alignSelf: 'center',
    maxWidth: 660,
    position: 'relative',
    zIndex: 1,
  },
  eyebrow: {
    color: themeCssVariables.accent.primary,
    fontSize: themeCssVariables.font.size.xxs,
    fontWeight: themeCssVariables.font.weight.semiBold,
    letterSpacing: '0.12em',
    margin: 0,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: themeCssVariables.font.color.primary,
    fontSize: 30,
    fontWeight: themeCssVariables.font.weight.semiBold,
    letterSpacing: '-0.03em',
    lineHeight: 1.15,
    margin: `${themeCssVariables.spacing[2]} 0`,
  },
  heroDescription: {
    color: themeCssVariables.font.color.secondary,
    fontSize: themeCssVariables.font.size.sm,
    lineHeight: 1.6,
    margin: 0,
  },
  heroActions: {
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    marginTop: themeCssVariables.spacing[4],
  },
  radarWrap: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    minHeight: 160,
    position: 'relative',
  },
  radarRingOuter: {
    border: `1px solid ${themeCssVariables.border.color.blue}`,
    borderRadius: '50%',
    height: 154,
    opacity: 0.36,
    position: 'absolute',
    width: 154,
  },
  radarRingMiddle: {
    border: `1px solid ${themeCssVariables.border.color.blue}`,
    borderRadius: '50%',
    height: 110,
    opacity: 0.5,
    position: 'absolute',
    width: 110,
  },
  radarRingInner: {
    background: themeCssVariables.background.transparent.blue,
    border: `1px solid ${themeCssVariables.border.color.blue}`,
    borderRadius: '50%',
    height: 70,
    position: 'absolute',
    width: 70,
  },
  radarValue: {
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.xl,
    fontWeight: themeCssVariables.font.weight.semiBold,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  radarLabel: {
    color: themeCssVariables.font.color.tertiary,
    display: 'block',
    fontSize: themeCssVariables.font.size.xxs,
    fontWeight: themeCssVariables.font.weight.regular,
    marginTop: themeCssVariables.spacing[1],
  },
  kpiGrid: {
    display: 'grid',
    gap: themeCssVariables.spacing[3],
    gridTemplateColumns: 'repeat(4, minmax(150px, 1fr))',
  },
  kpiContent: {
    alignItems: 'flex-end',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    justifyContent: 'space-between',
  },
  kpiValue: {
    fontSize: themeCssVariables.font.size.xl,
    fontWeight: themeCssVariables.font.weight.semiBold,
    letterSpacing: '-0.02em',
  },
  mainGrid: {
    alignItems: 'start',
    display: 'grid',
    gap: themeCssVariables.spacing[4],
    gridTemplateColumns: 'minmax(0, 1.35fr) minmax(300px, 0.65fr)',
  },
  sectionHeader: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    justifyContent: 'space-between',
  },
  signalList: {
    display: 'flex',
    flexDirection: 'column',
  },
  signalRow: {
    display: 'grid',
    gap: themeCssVariables.spacing[3],
    gridTemplateColumns: '10px minmax(0, 1fr) auto',
    padding: `${themeCssVariables.spacing[3]} 0`,
  },
  signalDot: {
    borderRadius: '50%',
    height: 8,
    marginTop: themeCssVariables.spacing[1],
    width: 8,
  },
  signalTitle: {
    fontSize: themeCssVariables.font.size.sm,
    fontWeight: themeCssVariables.font.weight.medium,
    margin: 0,
  },
  signalMeta: {
    alignItems: 'center',
    color: themeCssVariables.font.color.tertiary,
    display: 'flex',
    flexWrap: 'wrap',
    fontSize: themeCssVariables.font.size.xxs,
    gap: themeCssVariables.spacing[1],
    marginTop: themeCssVariables.spacing[1],
  },
  signalAction: {
    color: themeCssVariables.font.color.secondary,
    fontSize: themeCssVariables.font.size.xs,
    lineHeight: 1.45,
    margin: `${themeCssVariables.spacing[2]} 0 0`,
  },
  signalButtons: {
    alignItems: 'flex-end',
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[1],
  },
  opportunityList: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[3],
  },
  opportunityHeader: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    justifyContent: 'space-between',
  },
  opportunityName: {
    fontSize: themeCssVariables.font.size.sm,
    fontWeight: themeCssVariables.font.weight.medium,
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  opportunityMeta: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    margin: `${themeCssVariables.spacing[1]} 0 ${themeCssVariables.spacing[2]}`,
  },
  nextActionGrid: {
    display: 'grid',
    gap: themeCssVariables.spacing[2],
    gridTemplateColumns: 'repeat(3, minmax(220px, 1fr))',
  },
  nextActionCard: {
    cursor: 'pointer',
    minHeight: 118,
  },
  nextActionTitle: {
    fontSize: themeCssVariables.font.size.sm,
    fontWeight: themeCssVariables.font.weight.medium,
    lineHeight: 1.4,
    margin: 0,
  },
  empty: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.sm,
    padding: `${themeCssVariables.spacing[6]} ${themeCssVariables.spacing[3]}`,
    textAlign: 'center',
  },
  error: {
    color: themeCssVariables.font.color.danger,
    fontSize: themeCssVariables.font.size.sm,
    padding: themeCssVariables.spacing[4],
    textAlign: 'center',
  },
};
