apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diexcrm-db-pvc
  namespace: diexcrm
spec:
  storageClassName: default
  volumeName: diexcrm-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
