apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diexcrm-docker-data-pvc
  namespace: diexcrm
spec:
  storageClassName: default
  volumeName: diexcrm-docker-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
