import { type CSSProperties } from 'react';
import { themeCssVariables as importedThemeCssVariables } from 'twenty-ui/theme-constants';

type ThemeFallback = Record<PropertyKey, unknown>;

let themeFallback: ThemeFallback;

themeFallback = new Proxy({} as ThemeFallback, {
  get: (_target, property) =>
    property === Symbol.toPrimitive ? () => '' : themeFallback,
});

const themeCssVariables =
  importedThemeCssVariables ??
  (themeFallback as unknown as typeof importedThemeCssVariables);
const border = `1px solid ${themeCssVariables.border.color.light}`;

export const inboxStyles: Record<string, CSSProperties> = {
  root: {
    background: themeCssVariables.background.primary,
    border,
    borderRadius: themeCssVariables.border.radius.md,
    boxShadow: themeCssVariables.boxShadow.light,
    boxSizing: 'border-box',
    color: themeCssVariables.font.color.primary,
    display: 'grid',
    fontFamily: themeCssVariables.font.family,
    gridTemplateColumns:
      'minmax(270px, 0.9fr) minmax(420px, 1.7fr) minmax(260px, 0.9fr)',
    height: 'clamp(620px, calc(100dvh - 148px), 840px)',
    minWidth: 980,
    overflow: 'hidden',
    width: '100%',
  },
  panel: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    minWidth: 0,
  },
  leftPanel: {
    borderRight: border,
  },
  rightPanel: {
    borderLeft: border,
    background: themeCssVariables.background.secondary,
  },
  sectionHeader: {
    borderBottom: border,
    flexShrink: 0,
    padding: themeCssVariables.spacing[4],
  },
  titleRow: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    justifyContent: 'space-between',
  },
  title: {
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.lg,
    fontWeight: themeCssVariables.font.weight.semiBold,
    margin: 0,
  },
  subtitle: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xs,
    lineHeight: 1.45,
    margin: `${themeCssVariables.spacing[1]} 0 0`,
  },
  iconButton: {
    alignItems: 'center',
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.secondary,
    cursor: 'pointer',
    display: 'inline-flex',
    height: themeCssVariables.spacing[8],
    justifyContent: 'center',
    padding: 0,
    width: themeCssVariables.spacing[8],
  },
  searchWrap: {
    alignItems: 'center',
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    marginTop: themeCssVariables.spacing[3],
    padding: `0 ${themeCssVariables.spacing[3]}`,
  },
  searchInput: {
    background: 'transparent',
    border: 0,
    color: themeCssVariables.font.color.primary,
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.sm,
    height: themeCssVariables.spacing[8],
    minWidth: 0,
    outline: 'none',
    width: '100%',
  },
  filterRow: {
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    marginTop: themeCssVariables.spacing[2],
  },
  filterSelect: {
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.secondary,
    flex: 1,
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    height: themeCssVariables.spacing[8],
    minWidth: 0,
    outline: 'none',
    padding: `0 ${themeCssVariables.spacing[2]}`,
    width: '100%',
  },
  scrollArea: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
  conversationButton: {
    alignItems: 'flex-start',
    background: 'transparent',
    border: 0,
    borderBottom: border,
    color: themeCssVariables.font.color.primary,
    cursor: 'pointer',
    display: 'flex',
    gap: themeCssVariables.spacing[3],
    padding: themeCssVariables.spacing[3],
    textAlign: 'left',
    width: '100%',
  },
  conversationButtonSelected: {
    background: themeCssVariables.background.transparent.blue,
    boxShadow: `inset 3px 0 0 ${themeCssVariables.accent.primary}`,
  },
  avatar: {
    alignItems: 'center',
    background: themeCssVariables.background.tertiary,
    borderRadius: themeCssVariables.border.radius.rounded,
    color: themeCssVariables.font.color.secondary,
    display: 'flex',
    flexShrink: 0,
    fontSize: themeCssVariables.font.size.sm,
    fontWeight: themeCssVariables.font.weight.semiBold,
    height: themeCssVariables.spacing[9],
    justifyContent: 'center',
    overflow: 'hidden',
    width: themeCssVariables.spacing[9],
  },
  avatarImage: {
    height: '100%',
    objectFit: 'cover',
    width: '100%',
  },
  conversationBody: {
    flex: 1,
    minWidth: 0,
  },
  conversationTopLine: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
  },
  conversationName: {
    color: themeCssVariables.font.color.primary,
    flex: 1,
    fontSize: themeCssVariables.font.size.sm,
    fontWeight: themeCssVariables.font.weight.medium,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  conversationTime: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    whiteSpace: 'nowrap',
  },
  conversationPreviewRow: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[1],
    marginTop: themeCssVariables.spacing[1],
  },
  conversationPreview: {
    color: themeCssVariables.font.color.tertiary,
    flex: 1,
    fontSize: themeCssVariables.font.size.xs,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  unreadBadge: {
    alignItems: 'center',
    background: themeCssVariables.color.green,
    borderRadius: themeCssVariables.border.radius.pill,
    color: themeCssVariables.font.color.inverted,
    display: 'inline-flex',
    fontSize: themeCssVariables.font.size.xxs,
    fontWeight: themeCssVariables.font.weight.semiBold,
    height: themeCssVariables.spacing[4],
    justifyContent: 'center',
    minWidth: themeCssVariables.spacing[4],
    padding: `0 ${themeCssVariables.spacing[1]}`,
  },
  metadataRow: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: themeCssVariables.spacing[1],
    marginTop: themeCssVariables.spacing[2],
  },
  statusChip: {
    borderRadius: themeCssVariables.border.radius.pill,
    display: 'inline-flex',
    fontSize: themeCssVariables.font.size.xxs,
    fontWeight: themeCssVariables.font.weight.medium,
    lineHeight: 1,
    padding: `${themeCssVariables.spacing[1]} ${themeCssVariables.spacing[2]}`,
  },
  threadHeader: {
    alignItems: 'center',
    borderBottom: border,
    display: 'flex',
    flexShrink: 0,
    gap: themeCssVariables.spacing[3],
    minHeight: 68,
    padding: `0 ${themeCssVariables.spacing[4]}`,
  },
  threadIdentity: {
    flex: 1,
    minWidth: 0,
  },
  threadName: {
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.md,
    fontWeight: themeCssVariables.font.weight.semiBold,
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  threadHandle: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xs,
    marginTop: themeCssVariables.spacing[1],
  },
  headerActions: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
  },
  secondaryButton: {
    alignItems: 'center',
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.secondary,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    gap: themeCssVariables.spacing[1],
    height: themeCssVariables.spacing[8],
    justifyContent: 'center',
    padding: `0 ${themeCssVariables.spacing[3]}`,
  },
  primaryButton: {
    alignItems: 'center',
    background: themeCssVariables.accent.primary,
    border: '1px solid transparent',
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.inverted,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    gap: themeCssVariables.spacing[1],
    height: themeCssVariables.spacing[8],
    justifyContent: 'center',
    padding: `0 ${themeCssVariables.spacing[3]}`,
  },
  disabledButton: {
    cursor: 'not-allowed',
    opacity: 0.55,
  },
  messageList: {
    background: themeCssVariables.background.secondary,
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    gap: themeCssVariables.spacing[3],
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    padding: themeCssVariables.spacing[4],
  },
  messageRow: {
    display: 'flex',
    width: '100%',
  },
  messageBubble: {
    border,
    borderRadius: themeCssVariables.border.radius.md,
    boxShadow: themeCssVariables.boxShadow.light,
    boxSizing: 'border-box',
    maxWidth: '76%',
    padding: `${themeCssVariables.spacing[2]} ${themeCssVariables.spacing[3]}`,
  },
  incomingBubble: {
    background: themeCssVariables.background.primary,
    marginRight: 'auto',
  },
  outgoingBubble: {
    background: themeCssVariables.background.transparent.blue,
    borderColor: themeCssVariables.border.color.blue,
    marginLeft: 'auto',
  },
  internalBubble: {
    background: themeCssVariables.color.yellow2,
    borderColor: themeCssVariables.color.yellow6,
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '86%',
  },
  messageSender: {
    color: themeCssVariables.font.color.secondary,
    fontSize: themeCssVariables.font.size.xxs,
    fontWeight: themeCssVariables.font.weight.semiBold,
    marginBottom: themeCssVariables.spacing[1],
  },
  messageText: {
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.sm,
    lineHeight: 1.5,
    margin: 0,
    overflowWrap: 'anywhere',
    whiteSpace: 'pre-wrap',
  },
  messageMeta: {
    alignItems: 'center',
    color: themeCssVariables.font.color.tertiary,
    display: 'flex',
    fontSize: themeCssVariables.font.size.xxs,
    gap: themeCssVariables.spacing[1],
    justifyContent: 'flex-end',
    marginTop: themeCssVariables.spacing[1],
  },
  composer: {
    background: themeCssVariables.background.primary,
    borderTop: border,
    flexShrink: 0,
    padding: themeCssVariables.spacing[3],
  },
  aiTriagePanel: {
    background: themeCssVariables.background.transparent.blue,
    border: `1px solid ${themeCssVariables.border.color.blue}`,
    borderRadius: themeCssVariables.border.radius.md,
    marginBottom: themeCssVariables.spacing[3],
    padding: themeCssVariables.spacing[3],
  },
  aiTriageHeader: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    justifyContent: 'space-between',
  },
  aiTriageTitle: {
    alignItems: 'center',
    color: themeCssVariables.font.color.primary,
    display: 'flex',
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.semiBold,
    gap: themeCssVariables.spacing[1],
  },
  aiTriageConfidence: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
  },
  aiTriageSummary: {
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.xs,
    lineHeight: 1.45,
    margin: `${themeCssVariables.spacing[2]} 0 0`,
  },
  aiTriageRecommendation: {
    color: themeCssVariables.font.color.secondary,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    lineHeight: 1.45,
    margin: `${themeCssVariables.spacing[1]} 0 0`,
  },
  aiDraftRow: {
    alignItems: 'flex-end',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    marginTop: themeCssVariables.spacing[2],
  },
  aiDraftText: {
    background: themeCssVariables.background.primary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.primary,
    flex: 1,
    fontSize: themeCssVariables.font.size.xs,
    lineHeight: 1.45,
    margin: 0,
    maxHeight: 84,
    overflowY: 'auto',
    padding: themeCssVariables.spacing[2],
    whiteSpace: 'pre-wrap',
  },
  composerLabel: {
    alignItems: 'center',
    color: themeCssVariables.font.color.secondary,
    display: 'flex',
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    gap: themeCssVariables.spacing[1],
    marginBottom: themeCssVariables.spacing[2],
  },
  composerModeRow: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[1],
    marginBottom: themeCssVariables.spacing[2],
  },
  composerModeButton: {
    alignItems: 'center',
    background: 'transparent',
    border: 0,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.tertiary,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    gap: themeCssVariables.spacing[1],
    minHeight: themeCssVariables.spacing[7],
    padding: `0 ${themeCssVariables.spacing[2]}`,
  },
  composerModeButtonActive: {
    background: themeCssVariables.background.tertiary,
    color: themeCssVariables.font.color.primary,
  },
  externalComposer: {
    display: 'flex',
    flexDirection: 'column',
    gap: themeCssVariables.spacing[2],
  },
  savedReplyToolbar: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
  },
  savedReplyToolbarLabel: {
    alignItems: 'center',
    color: themeCssVariables.font.color.secondary,
    display: 'inline-flex',
    flexShrink: 0,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    gap: themeCssVariables.spacing[1],
  },
  savedReplySelect: {
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.secondary,
    flex: 1,
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    height: themeCssVariables.spacing[8],
    minWidth: 0,
    outline: 'none',
    padding: `0 ${themeCssVariables.spacing[2]}`,
  },
  savedReplyMatches: {
    background: themeCssVariables.background.primary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    boxShadow: themeCssVariables.boxShadow.light,
    display: 'flex',
    flexDirection: 'column',
    maxHeight: 180,
    overflowY: 'auto',
  },
  savedReplyOption: {
    alignItems: 'center',
    background: 'transparent',
    border: 0,
    borderBottom: border,
    color: themeCssVariables.font.color.primary,
    cursor: 'pointer',
    display: 'flex',
    fontFamily: themeCssVariables.font.family,
    gap: themeCssVariables.spacing[2],
    minHeight: themeCssVariables.spacing[8],
    padding: `0 ${themeCssVariables.spacing[3]}`,
    textAlign: 'left',
    width: '100%',
  },
  savedReplyShortcut: {
    color: themeCssVariables.accent.primary,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.semiBold,
  },
  savedReplyName: {
    color: themeCssVariables.font.color.primary,
    flex: 1,
    fontSize: themeCssVariables.font.size.xs,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  savedReplyCategory: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    whiteSpace: 'nowrap',
  },
  composerRow: {
    alignItems: 'flex-end',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
  },
  textarea: {
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    boxSizing: 'border-box',
    color: themeCssVariables.font.color.primary,
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.sm,
    lineHeight: 1.45,
    minHeight: 64,
    outline: 'none',
    padding: themeCssVariables.spacing[3],
    resize: 'none',
    width: '100%',
  },
  sendReview: {
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: themeCssVariables.border.radius.md,
    padding: themeCssVariables.spacing[3],
  },
  sendReviewMeta: {
    alignItems: 'center',
    color: themeCssVariables.font.color.secondary,
    display: 'flex',
    fontSize: themeCssVariables.font.size.xs,
    gap: themeCssVariables.spacing[1],
    justifyContent: 'space-between',
  },
  sendReviewText: {
    background: themeCssVariables.background.primary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.sm,
    lineHeight: 1.45,
    margin: `${themeCssVariables.spacing[2]} 0`,
    maxHeight: 112,
    overflowY: 'auto',
    padding: themeCssVariables.spacing[2],
    whiteSpace: 'pre-wrap',
  },
  sendReviewActions: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    justifyContent: 'flex-end',
  },
  composerHint: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    margin: `${themeCssVariables.spacing[2]} 0 0`,
  },
  contextScroll: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    padding: themeCssVariables.spacing[3],
  },
  contextSection: {
    marginBottom: themeCssVariables.spacing[4],
  },
  contextSectionTitle: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    fontWeight: themeCssVariables.font.weight.semiBold,
    letterSpacing: '0.08em',
    margin: `0 0 ${themeCssVariables.spacing[2]}`,
    textTransform: 'uppercase',
  },
  contextSectionHeader: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  labelPicker: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: themeCssVariables.spacing[1],
  },
  labelToggle: {
    alignItems: 'center',
    cursor: 'pointer',
    fontFamily: themeCssVariables.font.family,
    maxWidth: '100%',
  },
  contextCard: {
    alignItems: 'center',
    background: themeCssVariables.background.primary,
    border,
    borderRadius: themeCssVariables.border.radius.md,
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    marginBottom: themeCssVariables.spacing[2],
    minHeight: 48,
    padding: themeCssVariables.spacing[2],
  },
  contextCardIcon: {
    alignItems: 'center',
    background: themeCssVariables.background.tertiary,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.secondary,
    display: 'flex',
    flexShrink: 0,
    height: themeCssVariables.spacing[8],
    justifyContent: 'center',
    width: themeCssVariables.spacing[8],
  },
  contextCardBody: {
    flex: 1,
    minWidth: 0,
  },
  contextCardLabel: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
  },
  contextSelect: {
    background: 'transparent',
    border: 0,
    color: themeCssVariables.font.color.primary,
    display: 'block',
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    marginTop: themeCssVariables.spacing['0.5'],
    maxWidth: '100%',
    outline: 'none',
    padding: 0,
    width: '100%',
  },
  contextActionRow: {
    alignItems: 'center',
    display: 'flex',
    gap: themeCssVariables.spacing[1],
    marginTop: themeCssVariables.spacing[1],
  },
  contextPresetSelect: {
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.secondary,
    display: 'block',
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xxs,
    height: themeCssVariables.spacing[7],
    marginTop: themeCssVariables.spacing[1],
    maxWidth: '100%',
    outline: 'none',
    padding: `0 ${themeCssVariables.spacing[2]}`,
    width: '100%',
  },
  contextDateInput: {
    background: 'transparent',
    border: 0,
    color: themeCssVariables.font.color.primary,
    flex: 1,
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xxs,
    minWidth: 0,
    outline: 'none',
    padding: 0,
  },
  contextTextInput: {
    background: themeCssVariables.background.secondary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.primary,
    display: 'block',
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    height: themeCssVariables.spacing[8],
    marginTop: themeCssVariables.spacing[1],
    outline: 'none',
    padding: `0 ${themeCssVariables.spacing[2]}`,
    width: '100%',
  },
  contextCardValue: {
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    marginTop: themeCssVariables.spacing['0.5'],
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  textButton: {
    background: 'transparent',
    border: 0,
    color: themeCssVariables.accent.primary,
    cursor: 'pointer',
    fontFamily: themeCssVariables.font.family,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    padding: themeCssVariables.spacing[1],
  },
  emptyState: {
    alignItems: 'center',
    color: themeCssVariables.font.color.tertiary,
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    fontSize: themeCssVariables.font.size.sm,
    gap: themeCssVariables.spacing[2],
    justifyContent: 'center',
    lineHeight: 1.5,
    padding: themeCssVariables.spacing[6],
    textAlign: 'center',
  },
  errorState: {
    background: themeCssVariables.background.transparent.danger,
    border: `1px solid ${themeCssVariables.border.color.danger}`,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.danger,
    fontSize: themeCssVariables.font.size.xs,
    margin: themeCssVariables.spacing[3],
    padding: themeCssVariables.spacing[3],
  },
  skeleton: {
    background: themeCssVariables.background.tertiary,
    borderRadius: themeCssVariables.border.radius.sm,
    height: 52,
    margin: themeCssVariables.spacing[3],
  },
  taskCard: {
    alignItems: 'center',
    background: themeCssVariables.background.primary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    display: 'flex',
    gap: themeCssVariables.spacing[2],
    marginBottom: themeCssVariables.spacing[2],
    padding: themeCssVariables.spacing[2],
  },
  taskComposer: {
    background: themeCssVariables.background.tertiary,
    border,
    borderRadius: themeCssVariables.border.radius.md,
    display: 'grid',
    gap: themeCssVariables.spacing[2],
    marginBottom: themeCssVariables.spacing[2],
    padding: themeCssVariables.spacing[3],
  },
  taskCompleteButton: {
    alignItems: 'center',
    background: themeCssVariables.background.primary,
    border,
    borderRadius: themeCssVariables.border.radius.sm,
    color: themeCssVariables.font.color.secondary,
    cursor: 'pointer',
    display: 'flex',
    flexShrink: 0,
    height: themeCssVariables.spacing[7],
    justifyContent: 'center',
    width: themeCssVariables.spacing[7],
  },
  taskOpenButton: {
    alignItems: 'center',
    background: 'transparent',
    border: 0,
    color: themeCssVariables.font.color.secondary,
    cursor: 'pointer',
    display: 'flex',
    flex: 1,
    fontFamily: themeCssVariables.font.family,
    gap: themeCssVariables.spacing[2],
    minWidth: 0,
    padding: 0,
    textAlign: 'left',
  },
  taskTitle: {
    color: themeCssVariables.font.color.primary,
    fontSize: themeCssVariables.font.size.xs,
    fontWeight: themeCssVariables.font.weight.medium,
    margin: 0,
  },
  taskMeta: {
    color: themeCssVariables.font.color.tertiary,
    fontSize: themeCssVariables.font.size.xxs,
    marginTop: themeCssVariables.spacing[1],
  },
};

export const getStatusChipStyle = (status: string): CSSProperties => {
  const palette = {
    OPEN: {
      background: themeCssVariables.tag.background.green,
      color: themeCssVariables.tag.text.green,
    },
    PENDING: {
      background: themeCssVariables.tag.background.orange,
      color: themeCssVariables.tag.text.orange,
    },
    SNOOZED: {
      background: themeCssVariables.tag.background.blue,
      color: themeCssVariables.tag.text.blue,
    },
    RESOLVED: {
      background: themeCssVariables.tag.background.gray,
      color: themeCssVariables.tag.text.gray,
    },
  }[status] ?? {
    background: themeCssVariables.tag.background.gray,
    color: themeCssVariables.tag.text.gray,
  };

  return {
    ...inboxStyles.statusChip,
    ...palette,
  };
};

export const getPriorityChipStyle = (priority: string): CSSProperties => {
  const palette = {
    HIGH: {
      background: themeCssVariables.tag.background.orange,
      color: themeCssVariables.tag.text.orange,
    },
    URGENT: {
      background: themeCssVariables.tag.background.red,
      color: themeCssVariables.tag.text.red,
    },
  }[priority] ?? {
    background: themeCssVariables.tag.background.gray,
    color: themeCssVariables.tag.text.gray,
  };

  return {
    ...inboxStyles.statusChip,
    ...palette,
  };
};

export const getLabelChipStyle = (
  color: string,
  isActive = true,
): CSSProperties => {
  const palette = {
    BLUE: {
      background: themeCssVariables.tag.background.blue,
      color: themeCssVariables.tag.text.blue,
    },
    GREEN: {
      background: themeCssVariables.tag.background.green,
      color: themeCssVariables.tag.text.green,
    },
    ORANGE: {
      background: themeCssVariables.tag.background.orange,
      color: themeCssVariables.tag.text.orange,
    },
    RED: {
      background: themeCssVariables.tag.background.red,
      color: themeCssVariables.tag.text.red,
    },
    TURQUOISE: {
      background: themeCssVariables.tag.background.turquoise,
      color: themeCssVariables.tag.text.turquoise,
    },
    YELLOW: {
      background: themeCssVariables.tag.background.yellow,
      color: themeCssVariables.tag.text.yellow,
    },
    GRAY: {
      background: themeCssVariables.tag.background.gray,
      color: themeCssVariables.tag.text.gray,
    },
  }[color.toUpperCase()] ?? {
    background: themeCssVariables.tag.background.gray,
    color: themeCssVariables.tag.text.gray,
  };

  return {
    ...inboxStyles.statusChip,
    ...(isActive
      ? {
          ...palette,
          border: '1px solid transparent',
        }
      : {
          background: themeCssVariables.background.primary,
          border: `1px solid ${palette.color}`,
          color: palette.color,
          opacity: 0.76,
        }),
    maxWidth: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  };
};
